<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['doctors_token'])){
    $_SESSION['doctors_token'] = bin2hex(random_bytes(32));
    $_SESSION['doctors_token_time'] = time() + 3600;
    exit($_SESSION['doctors_token']);
  }

  if($_GET['token'] != $_SESSION['doctors_token'] || $_SESSION['doctors_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['doctors_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $doctors = new Doctors();
  if(!empty($_GET['id'])){$doctors->setId($_GET['id']);}
  if(!empty($_GET['user_id'])){$doctors->setUser_id($_GET['user_id']);}
  if(!empty($_GET['first_name'])){$doctors->setFirst_name($_GET['first_name']);}
  if(!empty($_GET['middle_name'])){$doctors->setMiddle_name($_GET['middle_name']);}
  if(!empty($_GET['last_name'])){$doctors->setLast_name($_GET['last_name']);}
  if(!empty($_GET['email'])){$doctors->setEmail($_GET['email']);}
  if(!empty($_GET['phone'])){$doctors->setPhone($_GET['phone']);}
  if(!empty($_GET['gender'])){$doctors->setGender($_GET['gender']);}
  if(!empty($_GET['dob'])){$doctors->setDob($_GET['dob']);}
  if(!empty($_GET['specialty'])){$doctors->setSpecialty($_GET['specialty']);}
  if(!empty($_GET['education'])){$doctors->setEducation($_GET['education']);}
  if(!empty($_GET['experience_years'])){$doctors->setExperience_years($_GET['experience_years']);}
  if(!empty($_GET['start_office_hour'])){$doctors->setStart_office_hour($_GET['start_office_hour']);}
  if(!empty($_GET['end_office_hour'])){$doctors->setEnd_office_hour($_GET['end_office_hour']);}
  if(!empty($_GET['bio'])){$doctors->setBio($_GET['bio']);}
  if(!empty($_GET['timee'])){$doctors->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$doctors->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$doctors->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$doctors->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$doctors->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($doctors->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($doctors->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($doctors->getLastRow()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($doctors->getFirstRow()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($doctors->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$doctors->getNumberOfRows());}
  if(!empty($_GET['getById'])){$doctors->setId($_GET['getById']); if($doctors->getById()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByUser_id'])){$doctors->setUser_id($_GET['getByUser_id']); if($doctors->getByUser_id()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByFirst_name'])){$doctors->setFirst_name($_GET['getByFirst_name']); if($doctors->getByFirst_name()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByMiddle_name'])){$doctors->setMiddle_name($_GET['getByMiddle_name']); if($doctors->getByMiddle_name()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByLast_name'])){$doctors->setLast_name($_GET['getByLast_name']); if($doctors->getByLast_name()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByEmail'])){$doctors->setEmail($_GET['getByEmail']); if($doctors->getByEmail()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByPhone'])){$doctors->setPhone($_GET['getByPhone']); if($doctors->getByPhone()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByGender'])){$doctors->setGender($_GET['getByGender']); if($doctors->getByGender()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByDob'])){$doctors->setDob($_GET['getByDob']); if($doctors->getByDob()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getBySpecialty'])){$doctors->setSpecialty($_GET['getBySpecialty']); if($doctors->getBySpecialty()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByEducation'])){$doctors->setEducation($_GET['getByEducation']); if($doctors->getByEducation()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByExperience_years'])){$doctors->setExperience_years($_GET['getByExperience_years']); if($doctors->getByExperience_years()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByStart_office_hour'])){$doctors->setStart_office_hour($_GET['getByStart_office_hour']); if($doctors->getByStart_office_hour()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByEnd_office_hour'])){$doctors->setEnd_office_hour($_GET['getByEnd_office_hour']); if($doctors->getByEnd_office_hour()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByBio'])){$doctors->setBio($_GET['getByBio']); if($doctors->getByBio()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$doctors->setTimee($_GET['getByTimee']); if($doctors->getByTimee()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$doctors->setTime($_GET['getByTime']); if($doctors->getByTime()){exit("this.id='{$doctors->getId()}', this.user_id='{$doctors->getUser_id()}', this.first_name='{$doctors->getFirst_name()}', this.middle_name='{$doctors->getMiddle_name()}', this.last_name='{$doctors->getLast_name()}', this.email='{$doctors->getEmail()}', this.phone='{$doctors->getPhone()}', this.gender='{$doctors->getGender()}', this.dob='{$doctors->getDob()}', this.specialty='{$doctors->getSpecialty()}', this.education='{$doctors->getEducation()}', this.experience_years='{$doctors->getExperience_years()}', this.start_office_hour='{$doctors->getStart_office_hour()}', this.end_office_hour='{$doctors->getEnd_office_hour()}', this.bio='{$doctors->getBio()}', this.timee='{$doctors->getTimee()}', this.time='{$doctors->getTime()}'");}}

?>