<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_disabilities_token'])){
    $_SESSION['logs_disabilities_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_disabilities_token_time'] = time() + 3600;
    exit($_SESSION['logs_disabilities_token']);
  }

  if($_GET['token'] != $_SESSION['logs_disabilities_token'] || $_SESSION['logs_disabilities_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_disabilities_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_disabilities = new Logs_disabilities();
  if(!empty($_GET['id'])){$logs_disabilities->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_disabilities->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_disabilities->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_disability_name'])){$logs_disabilities->setNew_disability_name($_GET['new_disability_name']);}
  if(!empty($_GET['new_onset_date'])){$logs_disabilities->setNew_onset_date($_GET['new_onset_date']);}
  if(!empty($_GET['new_notes'])){$logs_disabilities->setNew_notes($_GET['new_notes']);}
  if(!empty($_GET['logs_cdate'])){$logs_disabilities->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_disabilities->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_disabilities->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_disabilities->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_disabilities->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_disabilities->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_disabilities->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_disabilities->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_disabilities->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_disabilities->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_disabilities->getLastRow()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_disabilities->getFirstRow()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_disabilities->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_disabilities->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_disabilities->setId($_GET['getById']); if($logs_disabilities->getById()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_disabilities->setActionn($_GET['getByActionn']); if($logs_disabilities->getByActionn()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_disabilities->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_disabilities->getByNew_patient_id()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByNew_disability_name'])){$logs_disabilities->setNew_disability_name($_GET['getByNew_disability_name']); if($logs_disabilities->getByNew_disability_name()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByNew_onset_date'])){$logs_disabilities->setNew_onset_date($_GET['getByNew_onset_date']); if($logs_disabilities->getByNew_onset_date()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByNew_notes'])){$logs_disabilities->setNew_notes($_GET['getByNew_notes']); if($logs_disabilities->getByNew_notes()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_disabilities->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_disabilities->getByLogs_cdate()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_disabilities->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_disabilities->getByLogs_ctime()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_disabilities->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_disabilities->getByLog_ByUser()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_disabilities->setTimee($_GET['getByTimee']); if($logs_disabilities->getByTimee()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_disabilities->setTime($_GET['getByTime']); if($logs_disabilities->getByTime()){exit("this.id='{$logs_disabilities->getId()}', this.actionn='{$logs_disabilities->getActionn()}', this.new_patient_id='{$logs_disabilities->getNew_patient_id()}', this.new_disability_name='{$logs_disabilities->getNew_disability_name()}', this.new_onset_date='{$logs_disabilities->getNew_onset_date()}', this.new_notes='{$logs_disabilities->getNew_notes()}', this.logs_cdate='{$logs_disabilities->getLogs_cdate()}', this.logs_ctime='{$logs_disabilities->getLogs_ctime()}', this.log_ByUser='{$logs_disabilities->getLog_ByUser()}', this.timee='{$logs_disabilities->getTimee()}', this.time='{$logs_disabilities->getTime()}'");}}

?>