<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_prescriptions_token'])){
    $_SESSION['logs_prescriptions_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_prescriptions_token_time'] = time() + 3600;
    exit($_SESSION['logs_prescriptions_token']);
  }

  if($_GET['token'] != $_SESSION['logs_prescriptions_token'] || $_SESSION['logs_prescriptions_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_prescriptions_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_prescriptions = new Logs_prescriptions();
  if(!empty($_GET['id'])){$logs_prescriptions->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_prescriptions->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_prescriptions->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_doctor_id'])){$logs_prescriptions->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_medication_id'])){$logs_prescriptions->setNew_medication_id($_GET['new_medication_id']);}
  if(!empty($_GET['new_prescription_date'])){$logs_prescriptions->setNew_prescription_date($_GET['new_prescription_date']);}
  if(!empty($_GET['new_dosage'])){$logs_prescriptions->setNew_dosage($_GET['new_dosage']);}
  if(!empty($_GET['logs_cdate'])){$logs_prescriptions->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_prescriptions->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_prescriptions->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_prescriptions->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_prescriptions->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_prescriptions->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_prescriptions->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_prescriptions->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_prescriptions->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_prescriptions->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_prescriptions->getLastRow()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_prescriptions->getFirstRow()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_prescriptions->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_prescriptions->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_prescriptions->setId($_GET['getById']); if($logs_prescriptions->getById()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_prescriptions->setActionn($_GET['getByActionn']); if($logs_prescriptions->getByActionn()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_prescriptions->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_prescriptions->getByNew_patient_id()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_prescriptions->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_prescriptions->getByNew_doctor_id()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByNew_medication_id'])){$logs_prescriptions->setNew_medication_id($_GET['getByNew_medication_id']); if($logs_prescriptions->getByNew_medication_id()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByNew_prescription_date'])){$logs_prescriptions->setNew_prescription_date($_GET['getByNew_prescription_date']); if($logs_prescriptions->getByNew_prescription_date()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByNew_dosage'])){$logs_prescriptions->setNew_dosage($_GET['getByNew_dosage']); if($logs_prescriptions->getByNew_dosage()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_prescriptions->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_prescriptions->getByLogs_cdate()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_prescriptions->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_prescriptions->getByLogs_ctime()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_prescriptions->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_prescriptions->getByLog_ByUser()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_prescriptions->setTimee($_GET['getByTimee']); if($logs_prescriptions->getByTimee()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_prescriptions->setTime($_GET['getByTime']); if($logs_prescriptions->getByTime()){exit("this.id='{$logs_prescriptions->getId()}', this.actionn='{$logs_prescriptions->getActionn()}', this.new_patient_id='{$logs_prescriptions->getNew_patient_id()}', this.new_doctor_id='{$logs_prescriptions->getNew_doctor_id()}', this.new_medication_id='{$logs_prescriptions->getNew_medication_id()}', this.new_prescription_date='{$logs_prescriptions->getNew_prescription_date()}', this.new_dosage='{$logs_prescriptions->getNew_dosage()}', this.logs_cdate='{$logs_prescriptions->getLogs_cdate()}', this.logs_ctime='{$logs_prescriptions->getLogs_ctime()}', this.log_ByUser='{$logs_prescriptions->getLog_ByUser()}', this.timee='{$logs_prescriptions->getTimee()}', this.time='{$logs_prescriptions->getTime()}'");}}

?>