<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_medical_records_token'])){
    $_SESSION['logs_medical_records_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_medical_records_token_time'] = time() + 3600;
    exit($_SESSION['logs_medical_records_token']);
  }

  if($_GET['token'] != $_SESSION['logs_medical_records_token'] || $_SESSION['logs_medical_records_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_medical_records_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_medical_records = new Logs_medical_records();
  if(!empty($_GET['id'])){$logs_medical_records->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_medical_records->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_doctor_id'])){$logs_medical_records->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_patient_id'])){$logs_medical_records->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_record_date'])){$logs_medical_records->setNew_record_date($_GET['new_record_date']);}
  if(!empty($_GET['new_medical_condition'])){$logs_medical_records->setNew_medical_condition($_GET['new_medical_condition']);}
  if(!empty($_GET['new_height'])){$logs_medical_records->setNew_height($_GET['new_height']);}
  if(!empty($_GET['new_weight'])){$logs_medical_records->setNew_weight($_GET['new_weight']);}
  if(!empty($_GET['new_blood_pressure'])){$logs_medical_records->setNew_blood_pressure($_GET['new_blood_pressure']);}
  if(!empty($_GET['new_blood_sugar'])){$logs_medical_records->setNew_blood_sugar($_GET['new_blood_sugar']);}
  if(!empty($_GET['new_treatment'])){$logs_medical_records->setNew_treatment($_GET['new_treatment']);}
  if(!empty($_GET['new_description'])){$logs_medical_records->setNew_description($_GET['new_description']);}
  if(!empty($_GET['new_diagnosis_date'])){$logs_medical_records->setNew_diagnosis_date($_GET['new_diagnosis_date']);}
  if(!empty($_GET['logs_cdate'])){$logs_medical_records->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_medical_records->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_medical_records->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_medical_records->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_medical_records->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_medical_records->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_medical_records->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_medical_records->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_medical_records->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_medical_records->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_medical_records->getLastRow()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_medical_records->getFirstRow()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_medical_records->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_medical_records->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_medical_records->setId($_GET['getById']); if($logs_medical_records->getById()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_medical_records->setActionn($_GET['getByActionn']); if($logs_medical_records->getByActionn()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_medical_records->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_medical_records->getByNew_doctor_id()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_medical_records->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_medical_records->getByNew_patient_id()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_record_date'])){$logs_medical_records->setNew_record_date($_GET['getByNew_record_date']); if($logs_medical_records->getByNew_record_date()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_medical_condition'])){$logs_medical_records->setNew_medical_condition($_GET['getByNew_medical_condition']); if($logs_medical_records->getByNew_medical_condition()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_height'])){$logs_medical_records->setNew_height($_GET['getByNew_height']); if($logs_medical_records->getByNew_height()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_weight'])){$logs_medical_records->setNew_weight($_GET['getByNew_weight']); if($logs_medical_records->getByNew_weight()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_blood_pressure'])){$logs_medical_records->setNew_blood_pressure($_GET['getByNew_blood_pressure']); if($logs_medical_records->getByNew_blood_pressure()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_blood_sugar'])){$logs_medical_records->setNew_blood_sugar($_GET['getByNew_blood_sugar']); if($logs_medical_records->getByNew_blood_sugar()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_treatment'])){$logs_medical_records->setNew_treatment($_GET['getByNew_treatment']); if($logs_medical_records->getByNew_treatment()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_description'])){$logs_medical_records->setNew_description($_GET['getByNew_description']); if($logs_medical_records->getByNew_description()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByNew_diagnosis_date'])){$logs_medical_records->setNew_diagnosis_date($_GET['getByNew_diagnosis_date']); if($logs_medical_records->getByNew_diagnosis_date()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_medical_records->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_medical_records->getByLogs_cdate()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_medical_records->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_medical_records->getByLogs_ctime()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_medical_records->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_medical_records->getByLog_ByUser()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_medical_records->setTimee($_GET['getByTimee']); if($logs_medical_records->getByTimee()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_medical_records->setTime($_GET['getByTime']); if($logs_medical_records->getByTime()){exit("this.id='{$logs_medical_records->getId()}', this.actionn='{$logs_medical_records->getActionn()}', this.new_doctor_id='{$logs_medical_records->getNew_doctor_id()}', this.new_patient_id='{$logs_medical_records->getNew_patient_id()}', this.new_record_date='{$logs_medical_records->getNew_record_date()}', this.new_medical_condition='{$logs_medical_records->getNew_medical_condition()}', this.new_height='{$logs_medical_records->getNew_height()}', this.new_weight='{$logs_medical_records->getNew_weight()}', this.new_blood_pressure='{$logs_medical_records->getNew_blood_pressure()}', this.new_blood_sugar='{$logs_medical_records->getNew_blood_sugar()}', this.new_treatment='{$logs_medical_records->getNew_treatment()}', this.new_description='{$logs_medical_records->getNew_description()}', this.new_diagnosis_date='{$logs_medical_records->getNew_diagnosis_date()}', this.logs_cdate='{$logs_medical_records->getLogs_cdate()}', this.logs_ctime='{$logs_medical_records->getLogs_ctime()}', this.log_ByUser='{$logs_medical_records->getLog_ByUser()}', this.timee='{$logs_medical_records->getTimee()}', this.time='{$logs_medical_records->getTime()}'");}}

?>