<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_patient_history_token'])){
    $_SESSION['logs_patient_history_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_patient_history_token_time'] = time() + 3600;
    exit($_SESSION['logs_patient_history_token']);
  }

  if($_GET['token'] != $_SESSION['logs_patient_history_token'] || $_SESSION['logs_patient_history_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_patient_history_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_patient_history = new Logs_patient_history();
  if(!empty($_GET['id'])){$logs_patient_history->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_patient_history->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_files_id'])){$logs_patient_history->setNew_files_id($_GET['new_files_id']);}
  if(!empty($_GET['new_diagnosis'])){$logs_patient_history->setNew_diagnosis($_GET['new_diagnosis']);}
  if(!empty($_GET['new_treatment'])){$logs_patient_history->setNew_treatment($_GET['new_treatment']);}
  if(!empty($_GET['new_notes'])){$logs_patient_history->setNew_notes($_GET['new_notes']);}
  if(!empty($_GET['new_created_at'])){$logs_patient_history->setNew_created_at($_GET['new_created_at']);}
  if(!empty($_GET['new_updated_at'])){$logs_patient_history->setNew_updated_at($_GET['new_updated_at']);}
  if(!empty($_GET['logs_cdate'])){$logs_patient_history->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_patient_history->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_patient_history->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_patient_history->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_patient_history->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_patient_history->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_patient_history->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_patient_history->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_patient_history->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_patient_history->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_patient_history->getLastRow()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_patient_history->getFirstRow()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_patient_history->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_patient_history->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_patient_history->setId($_GET['getById']); if($logs_patient_history->getById()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_patient_history->setActionn($_GET['getByActionn']); if($logs_patient_history->getByActionn()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByNew_files_id'])){$logs_patient_history->setNew_files_id($_GET['getByNew_files_id']); if($logs_patient_history->getByNew_files_id()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByNew_diagnosis'])){$logs_patient_history->setNew_diagnosis($_GET['getByNew_diagnosis']); if($logs_patient_history->getByNew_diagnosis()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByNew_treatment'])){$logs_patient_history->setNew_treatment($_GET['getByNew_treatment']); if($logs_patient_history->getByNew_treatment()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByNew_notes'])){$logs_patient_history->setNew_notes($_GET['getByNew_notes']); if($logs_patient_history->getByNew_notes()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByNew_created_at'])){$logs_patient_history->setNew_created_at($_GET['getByNew_created_at']); if($logs_patient_history->getByNew_created_at()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByNew_updated_at'])){$logs_patient_history->setNew_updated_at($_GET['getByNew_updated_at']); if($logs_patient_history->getByNew_updated_at()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_patient_history->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_patient_history->getByLogs_cdate()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_patient_history->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_patient_history->getByLogs_ctime()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_patient_history->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_patient_history->getByLog_ByUser()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_patient_history->setTimee($_GET['getByTimee']); if($logs_patient_history->getByTimee()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_patient_history->setTime($_GET['getByTime']); if($logs_patient_history->getByTime()){exit("this.id='{$logs_patient_history->getId()}', this.actionn='{$logs_patient_history->getActionn()}', this.new_files_id='{$logs_patient_history->getNew_files_id()}', this.new_diagnosis='{$logs_patient_history->getNew_diagnosis()}', this.new_treatment='{$logs_patient_history->getNew_treatment()}', this.new_notes='{$logs_patient_history->getNew_notes()}', this.new_created_at='{$logs_patient_history->getNew_created_at()}', this.new_updated_at='{$logs_patient_history->getNew_updated_at()}', this.logs_cdate='{$logs_patient_history->getLogs_cdate()}', this.logs_ctime='{$logs_patient_history->getLogs_ctime()}', this.log_ByUser='{$logs_patient_history->getLog_ByUser()}', this.timee='{$logs_patient_history->getTimee()}', this.time='{$logs_patient_history->getTime()}'");}}

?>