<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_patients_token'])){
    $_SESSION['logs_patients_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_patients_token_time'] = time() + 3600;
    exit($_SESSION['logs_patients_token']);
  }

  if($_GET['token'] != $_SESSION['logs_patients_token'] || $_SESSION['logs_patients_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_patients_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_patients = new Logs_patients();
  if(!empty($_GET['id'])){$logs_patients->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_patients->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_user_id'])){$logs_patients->setNew_user_id($_GET['new_user_id']);}
  if(!empty($_GET['new_first_name'])){$logs_patients->setNew_first_name($_GET['new_first_name']);}
  if(!empty($_GET['new_middle_name'])){$logs_patients->setNew_middle_name($_GET['new_middle_name']);}
  if(!empty($_GET['new_last_name'])){$logs_patients->setNew_last_name($_GET['new_last_name']);}
  if(!empty($_GET['new_date_of_birth'])){$logs_patients->setNew_date_of_birth($_GET['new_date_of_birth']);}
  if(!empty($_GET['new_gender'])){$logs_patients->setNew_gender($_GET['new_gender']);}
  if(!empty($_GET['new_address'])){$logs_patients->setNew_address($_GET['new_address']);}
  if(!empty($_GET['new_city'])){$logs_patients->setNew_city($_GET['new_city']);}
  if(!empty($_GET['new_state'])){$logs_patients->setNew_state($_GET['new_state']);}
  if(!empty($_GET['new_zip_code'])){$logs_patients->setNew_zip_code($_GET['new_zip_code']);}
  if(!empty($_GET['new_phone_number'])){$logs_patients->setNew_phone_number($_GET['new_phone_number']);}
  if(!empty($_GET['new_email'])){$logs_patients->setNew_email($_GET['new_email']);}
  if(!empty($_GET['logs_cdate'])){$logs_patients->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_patients->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_patients->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_patients->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_patients->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_patients->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_patients->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_patients->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_patients->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_patients->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_patients->getLastRow()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_patients->getFirstRow()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_patients->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_patients->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_patients->setId($_GET['getById']); if($logs_patients->getById()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_patients->setActionn($_GET['getByActionn']); if($logs_patients->getByActionn()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_user_id'])){$logs_patients->setNew_user_id($_GET['getByNew_user_id']); if($logs_patients->getByNew_user_id()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_first_name'])){$logs_patients->setNew_first_name($_GET['getByNew_first_name']); if($logs_patients->getByNew_first_name()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_middle_name'])){$logs_patients->setNew_middle_name($_GET['getByNew_middle_name']); if($logs_patients->getByNew_middle_name()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_last_name'])){$logs_patients->setNew_last_name($_GET['getByNew_last_name']); if($logs_patients->getByNew_last_name()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_date_of_birth'])){$logs_patients->setNew_date_of_birth($_GET['getByNew_date_of_birth']); if($logs_patients->getByNew_date_of_birth()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_gender'])){$logs_patients->setNew_gender($_GET['getByNew_gender']); if($logs_patients->getByNew_gender()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_address'])){$logs_patients->setNew_address($_GET['getByNew_address']); if($logs_patients->getByNew_address()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_city'])){$logs_patients->setNew_city($_GET['getByNew_city']); if($logs_patients->getByNew_city()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_state'])){$logs_patients->setNew_state($_GET['getByNew_state']); if($logs_patients->getByNew_state()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_zip_code'])){$logs_patients->setNew_zip_code($_GET['getByNew_zip_code']); if($logs_patients->getByNew_zip_code()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_phone_number'])){$logs_patients->setNew_phone_number($_GET['getByNew_phone_number']); if($logs_patients->getByNew_phone_number()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByNew_email'])){$logs_patients->setNew_email($_GET['getByNew_email']); if($logs_patients->getByNew_email()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_patients->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_patients->getByLogs_cdate()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_patients->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_patients->getByLogs_ctime()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_patients->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_patients->getByLog_ByUser()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_patients->setTimee($_GET['getByTimee']); if($logs_patients->getByTimee()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_patients->setTime($_GET['getByTime']); if($logs_patients->getByTime()){exit("this.id='{$logs_patients->getId()}', this.actionn='{$logs_patients->getActionn()}', this.new_user_id='{$logs_patients->getNew_user_id()}', this.new_first_name='{$logs_patients->getNew_first_name()}', this.new_middle_name='{$logs_patients->getNew_middle_name()}', this.new_last_name='{$logs_patients->getNew_last_name()}', this.new_date_of_birth='{$logs_patients->getNew_date_of_birth()}', this.new_gender='{$logs_patients->getNew_gender()}', this.new_address='{$logs_patients->getNew_address()}', this.new_city='{$logs_patients->getNew_city()}', this.new_state='{$logs_patients->getNew_state()}', this.new_zip_code='{$logs_patients->getNew_zip_code()}', this.new_phone_number='{$logs_patients->getNew_phone_number()}', this.new_email='{$logs_patients->getNew_email()}', this.logs_cdate='{$logs_patients->getLogs_cdate()}', this.logs_ctime='{$logs_patients->getLogs_ctime()}', this.log_ByUser='{$logs_patients->getLog_ByUser()}', this.timee='{$logs_patients->getTimee()}', this.time='{$logs_patients->getTime()}'");}}

?>