<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_surgeries_token'])){
    $_SESSION['logs_surgeries_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_surgeries_token_time'] = time() + 3600;
    exit($_SESSION['logs_surgeries_token']);
  }

  if($_GET['token'] != $_SESSION['logs_surgeries_token'] || $_SESSION['logs_surgeries_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_surgeries_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_surgeries = new Logs_surgeries();
  if(!empty($_GET['id'])){$logs_surgeries->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_surgeries->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_surgeries->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_surgery_name'])){$logs_surgeries->setNew_surgery_name($_GET['new_surgery_name']);}
  if(!empty($_GET['new_surgery_date'])){$logs_surgeries->setNew_surgery_date($_GET['new_surgery_date']);}
  if(!empty($_GET['new_notes'])){$logs_surgeries->setNew_notes($_GET['new_notes']);}
  if(!empty($_GET['logs_cdate'])){$logs_surgeries->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_surgeries->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_surgeries->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_surgeries->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_surgeries->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_surgeries->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_surgeries->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_surgeries->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_surgeries->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_surgeries->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_surgeries->getLastRow()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_surgeries->getFirstRow()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_surgeries->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_surgeries->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_surgeries->setId($_GET['getById']); if($logs_surgeries->getById()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_surgeries->setActionn($_GET['getByActionn']); if($logs_surgeries->getByActionn()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_surgeries->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_surgeries->getByNew_patient_id()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByNew_surgery_name'])){$logs_surgeries->setNew_surgery_name($_GET['getByNew_surgery_name']); if($logs_surgeries->getByNew_surgery_name()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByNew_surgery_date'])){$logs_surgeries->setNew_surgery_date($_GET['getByNew_surgery_date']); if($logs_surgeries->getByNew_surgery_date()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByNew_notes'])){$logs_surgeries->setNew_notes($_GET['getByNew_notes']); if($logs_surgeries->getByNew_notes()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_surgeries->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_surgeries->getByLogs_cdate()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_surgeries->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_surgeries->getByLogs_ctime()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_surgeries->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_surgeries->getByLog_ByUser()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_surgeries->setTimee($_GET['getByTimee']); if($logs_surgeries->getByTimee()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_surgeries->setTime($_GET['getByTime']); if($logs_surgeries->getByTime()){exit("this.id='{$logs_surgeries->getId()}', this.actionn='{$logs_surgeries->getActionn()}', this.new_patient_id='{$logs_surgeries->getNew_patient_id()}', this.new_surgery_name='{$logs_surgeries->getNew_surgery_name()}', this.new_surgery_date='{$logs_surgeries->getNew_surgery_date()}', this.new_notes='{$logs_surgeries->getNew_notes()}', this.logs_cdate='{$logs_surgeries->getLogs_cdate()}', this.logs_ctime='{$logs_surgeries->getLogs_ctime()}', this.log_ByUser='{$logs_surgeries->getLog_ByUser()}', this.timee='{$logs_surgeries->getTimee()}', this.time='{$logs_surgeries->getTime()}'");}}

?>