<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_allergies_token'])){
    $_SESSION['logs_allergies_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_allergies_token_time'] = time() + 3600;
    exit($_SESSION['logs_allergies_token']);
  }

  if($_GET['token'] != $_SESSION['logs_allergies_token'] || $_SESSION['logs_allergies_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_allergies_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_allergies = new Logs_allergies();
  if(!empty($_GET['id'])){$logs_allergies->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_allergies->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_allergies->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_Medication_allergies'])){$logs_allergies->setNew_Medication_allergies($_GET['new_Medication_allergies']);}
  if(!empty($_GET['new_name'])){$logs_allergies->setNew_name($_GET['new_name']);}
  if(!empty($_GET['new_severity'])){$logs_allergies->setNew_severity($_GET['new_severity']);}
  if(!empty($_GET['logs_cdate'])){$logs_allergies->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_allergies->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_allergies->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_allergies->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_allergies->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_allergies->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_allergies->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_allergies->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_allergies->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_allergies->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_allergies->getLastRow()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_allergies->getFirstRow()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_allergies->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_allergies->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_allergies->setId($_GET['getById']); if($logs_allergies->getById()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_allergies->setActionn($_GET['getByActionn']); if($logs_allergies->getByActionn()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_allergies->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_allergies->getByNew_patient_id()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByNew_Medication_allergies'])){$logs_allergies->setNew_Medication_allergies($_GET['getByNew_Medication_allergies']); if($logs_allergies->getByNew_Medication_allergies()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByNew_name'])){$logs_allergies->setNew_name($_GET['getByNew_name']); if($logs_allergies->getByNew_name()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByNew_severity'])){$logs_allergies->setNew_severity($_GET['getByNew_severity']); if($logs_allergies->getByNew_severity()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_allergies->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_allergies->getByLogs_cdate()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_allergies->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_allergies->getByLogs_ctime()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_allergies->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_allergies->getByLog_ByUser()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_allergies->setTimee($_GET['getByTimee']); if($logs_allergies->getByTimee()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_allergies->setTime($_GET['getByTime']); if($logs_allergies->getByTime()){exit("this.id='{$logs_allergies->getId()}', this.actionn='{$logs_allergies->getActionn()}', this.new_patient_id='{$logs_allergies->getNew_patient_id()}', this.new_Medication_allergies='{$logs_allergies->getNew_Medication_allergies()}', this.new_name='{$logs_allergies->getNew_name()}', this.new_severity='{$logs_allergies->getNew_severity()}', this.logs_cdate='{$logs_allergies->getLogs_cdate()}', this.logs_ctime='{$logs_allergies->getLogs_ctime()}', this.log_ByUser='{$logs_allergies->getLog_ByUser()}', this.timee='{$logs_allergies->getTimee()}', this.time='{$logs_allergies->getTime()}'");}}

?>