<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_symptoms_token'])){
    $_SESSION['logs_symptoms_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_symptoms_token_time'] = time() + 3600;
    exit($_SESSION['logs_symptoms_token']);
  }

  if($_GET['token'] != $_SESSION['logs_symptoms_token'] || $_SESSION['logs_symptoms_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_symptoms_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_symptoms = new Logs_symptoms();
  if(!empty($_GET['id'])){$logs_symptoms->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_symptoms->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_symptoms->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_symptom_name'])){$logs_symptoms->setNew_symptom_name($_GET['new_symptom_name']);}
  if(!empty($_GET['new_start_date'])){$logs_symptoms->setNew_start_date($_GET['new_start_date']);}
  if(!empty($_GET['new_end_date'])){$logs_symptoms->setNew_end_date($_GET['new_end_date']);}
  if(!empty($_GET['new_notes'])){$logs_symptoms->setNew_notes($_GET['new_notes']);}
  if(!empty($_GET['logs_cdate'])){$logs_symptoms->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_symptoms->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_symptoms->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['new_timee'])){$logs_symptoms->setNew_timee($_GET['new_timee']);}
  if(!empty($_GET['time'])){$logs_symptoms->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_symptoms->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_symptoms->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_symptoms->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_symptoms->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_symptoms->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_symptoms->getLastRow()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_symptoms->getFirstRow()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_symptoms->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_symptoms->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_symptoms->setId($_GET['getById']); if($logs_symptoms->getById()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_symptoms->setActionn($_GET['getByActionn']); if($logs_symptoms->getByActionn()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_symptoms->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_symptoms->getByNew_patient_id()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByNew_symptom_name'])){$logs_symptoms->setNew_symptom_name($_GET['getByNew_symptom_name']); if($logs_symptoms->getByNew_symptom_name()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByNew_start_date'])){$logs_symptoms->setNew_start_date($_GET['getByNew_start_date']); if($logs_symptoms->getByNew_start_date()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByNew_end_date'])){$logs_symptoms->setNew_end_date($_GET['getByNew_end_date']); if($logs_symptoms->getByNew_end_date()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByNew_notes'])){$logs_symptoms->setNew_notes($_GET['getByNew_notes']); if($logs_symptoms->getByNew_notes()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_symptoms->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_symptoms->getByLogs_cdate()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_symptoms->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_symptoms->getByLogs_ctime()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_symptoms->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_symptoms->getByLog_ByUser()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByNew_timee'])){$logs_symptoms->setNew_timee($_GET['getByNew_timee']); if($logs_symptoms->getByNew_timee()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_symptoms->setTime($_GET['getByTime']); if($logs_symptoms->getByTime()){exit("this.id='{$logs_symptoms->getId()}', this.actionn='{$logs_symptoms->getActionn()}', this.new_patient_id='{$logs_symptoms->getNew_patient_id()}', this.new_symptom_name='{$logs_symptoms->getNew_symptom_name()}', this.new_start_date='{$logs_symptoms->getNew_start_date()}', this.new_end_date='{$logs_symptoms->getNew_end_date()}', this.new_notes='{$logs_symptoms->getNew_notes()}', this.logs_cdate='{$logs_symptoms->getLogs_cdate()}', this.logs_ctime='{$logs_symptoms->getLogs_ctime()}', this.log_ByUser='{$logs_symptoms->getLog_ByUser()}', this.new_timee='{$logs_symptoms->getNew_timee()}', this.time='{$logs_symptoms->getTime()}'");}}

?>