<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_doctors_token'])){
    $_SESSION['logs_doctors_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_doctors_token_time'] = time() + 3600;
    exit($_SESSION['logs_doctors_token']);
  }

  if($_GET['token'] != $_SESSION['logs_doctors_token'] || $_SESSION['logs_doctors_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_doctors_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_doctors = new Logs_doctors();
  if(!empty($_GET['id'])){$logs_doctors->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_doctors->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_user_id'])){$logs_doctors->setNew_user_id($_GET['new_user_id']);}
  if(!empty($_GET['new_first_name'])){$logs_doctors->setNew_first_name($_GET['new_first_name']);}
  if(!empty($_GET['new_middle_name'])){$logs_doctors->setNew_middle_name($_GET['new_middle_name']);}
  if(!empty($_GET['new_last_name'])){$logs_doctors->setNew_last_name($_GET['new_last_name']);}
  if(!empty($_GET['new_email'])){$logs_doctors->setNew_email($_GET['new_email']);}
  if(!empty($_GET['new_phone'])){$logs_doctors->setNew_phone($_GET['new_phone']);}
  if(!empty($_GET['new_gender'])){$logs_doctors->setNew_gender($_GET['new_gender']);}
  if(!empty($_GET['new_dob'])){$logs_doctors->setNew_dob($_GET['new_dob']);}
  if(!empty($_GET['new_specialty'])){$logs_doctors->setNew_specialty($_GET['new_specialty']);}
  if(!empty($_GET['new_education'])){$logs_doctors->setNew_education($_GET['new_education']);}
  if(!empty($_GET['new_experience_years'])){$logs_doctors->setNew_experience_years($_GET['new_experience_years']);}
  if(!empty($_GET['new_start_office_hour'])){$logs_doctors->setNew_start_office_hour($_GET['new_start_office_hour']);}
  if(!empty($_GET['new_end_office_hour'])){$logs_doctors->setNew_end_office_hour($_GET['new_end_office_hour']);}
  if(!empty($_GET['new_bio'])){$logs_doctors->setNew_bio($_GET['new_bio']);}
  if(!empty($_GET['logs_cdate'])){$logs_doctors->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_doctors->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_doctors->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_doctors->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_doctors->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_doctors->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_doctors->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_doctors->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_doctors->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_doctors->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_doctors->getLastRow()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_doctors->getFirstRow()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_doctors->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_doctors->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_doctors->setId($_GET['getById']); if($logs_doctors->getById()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_doctors->setActionn($_GET['getByActionn']); if($logs_doctors->getByActionn()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_user_id'])){$logs_doctors->setNew_user_id($_GET['getByNew_user_id']); if($logs_doctors->getByNew_user_id()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_first_name'])){$logs_doctors->setNew_first_name($_GET['getByNew_first_name']); if($logs_doctors->getByNew_first_name()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_middle_name'])){$logs_doctors->setNew_middle_name($_GET['getByNew_middle_name']); if($logs_doctors->getByNew_middle_name()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_last_name'])){$logs_doctors->setNew_last_name($_GET['getByNew_last_name']); if($logs_doctors->getByNew_last_name()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_email'])){$logs_doctors->setNew_email($_GET['getByNew_email']); if($logs_doctors->getByNew_email()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_phone'])){$logs_doctors->setNew_phone($_GET['getByNew_phone']); if($logs_doctors->getByNew_phone()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_gender'])){$logs_doctors->setNew_gender($_GET['getByNew_gender']); if($logs_doctors->getByNew_gender()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_dob'])){$logs_doctors->setNew_dob($_GET['getByNew_dob']); if($logs_doctors->getByNew_dob()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_specialty'])){$logs_doctors->setNew_specialty($_GET['getByNew_specialty']); if($logs_doctors->getByNew_specialty()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_education'])){$logs_doctors->setNew_education($_GET['getByNew_education']); if($logs_doctors->getByNew_education()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_experience_years'])){$logs_doctors->setNew_experience_years($_GET['getByNew_experience_years']); if($logs_doctors->getByNew_experience_years()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_start_office_hour'])){$logs_doctors->setNew_start_office_hour($_GET['getByNew_start_office_hour']); if($logs_doctors->getByNew_start_office_hour()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_end_office_hour'])){$logs_doctors->setNew_end_office_hour($_GET['getByNew_end_office_hour']); if($logs_doctors->getByNew_end_office_hour()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByNew_bio'])){$logs_doctors->setNew_bio($_GET['getByNew_bio']); if($logs_doctors->getByNew_bio()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_doctors->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_doctors->getByLogs_cdate()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_doctors->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_doctors->getByLogs_ctime()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_doctors->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_doctors->getByLog_ByUser()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_doctors->setTimee($_GET['getByTimee']); if($logs_doctors->getByTimee()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_doctors->setTime($_GET['getByTime']); if($logs_doctors->getByTime()){exit("this.id='{$logs_doctors->getId()}', this.actionn='{$logs_doctors->getActionn()}', this.new_user_id='{$logs_doctors->getNew_user_id()}', this.new_first_name='{$logs_doctors->getNew_first_name()}', this.new_middle_name='{$logs_doctors->getNew_middle_name()}', this.new_last_name='{$logs_doctors->getNew_last_name()}', this.new_email='{$logs_doctors->getNew_email()}', this.new_phone='{$logs_doctors->getNew_phone()}', this.new_gender='{$logs_doctors->getNew_gender()}', this.new_dob='{$logs_doctors->getNew_dob()}', this.new_specialty='{$logs_doctors->getNew_specialty()}', this.new_education='{$logs_doctors->getNew_education()}', this.new_experience_years='{$logs_doctors->getNew_experience_years()}', this.new_start_office_hour='{$logs_doctors->getNew_start_office_hour()}', this.new_end_office_hour='{$logs_doctors->getNew_end_office_hour()}', this.new_bio='{$logs_doctors->getNew_bio()}', this.logs_cdate='{$logs_doctors->getLogs_cdate()}', this.logs_ctime='{$logs_doctors->getLogs_ctime()}', this.log_ByUser='{$logs_doctors->getLog_ByUser()}', this.timee='{$logs_doctors->getTimee()}', this.time='{$logs_doctors->getTime()}'");}}

?>