<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_patient_files_token'])){
    $_SESSION['logs_patient_files_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_patient_files_token_time'] = time() + 3600;
    exit($_SESSION['logs_patient_files_token']);
  }

  if($_GET['token'] != $_SESSION['logs_patient_files_token'] || $_SESSION['logs_patient_files_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_patient_files_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_patient_files = new Logs_patient_files();
  if(!empty($_GET['id'])){$logs_patient_files->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_patient_files->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_patient_files->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_doctor_id'])){$logs_patient_files->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_file_name'])){$logs_patient_files->setNew_file_name($_GET['new_file_name']);}
  if(!empty($_GET['new_file_type'])){$logs_patient_files->setNew_file_type($_GET['new_file_type']);}
  if(!empty($_GET['new_file_path'])){$logs_patient_files->setNew_file_path($_GET['new_file_path']);}
  if(!empty($_GET['new_created_at'])){$logs_patient_files->setNew_created_at($_GET['new_created_at']);}
  if(!empty($_GET['logs_cdate'])){$logs_patient_files->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_patient_files->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_patient_files->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_patient_files->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_patient_files->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_patient_files->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_patient_files->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_patient_files->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_patient_files->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_patient_files->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_patient_files->getLastRow()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_patient_files->getFirstRow()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_patient_files->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_patient_files->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_patient_files->setId($_GET['getById']); if($logs_patient_files->getById()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_patient_files->setActionn($_GET['getByActionn']); if($logs_patient_files->getByActionn()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_patient_files->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_patient_files->getByNew_patient_id()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_patient_files->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_patient_files->getByNew_doctor_id()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByNew_file_name'])){$logs_patient_files->setNew_file_name($_GET['getByNew_file_name']); if($logs_patient_files->getByNew_file_name()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByNew_file_type'])){$logs_patient_files->setNew_file_type($_GET['getByNew_file_type']); if($logs_patient_files->getByNew_file_type()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByNew_file_path'])){$logs_patient_files->setNew_file_path($_GET['getByNew_file_path']); if($logs_patient_files->getByNew_file_path()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByNew_created_at'])){$logs_patient_files->setNew_created_at($_GET['getByNew_created_at']); if($logs_patient_files->getByNew_created_at()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_patient_files->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_patient_files->getByLogs_cdate()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_patient_files->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_patient_files->getByLogs_ctime()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_patient_files->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_patient_files->getByLog_ByUser()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_patient_files->setTimee($_GET['getByTimee']); if($logs_patient_files->getByTimee()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_patient_files->setTime($_GET['getByTime']); if($logs_patient_files->getByTime()){exit("this.id='{$logs_patient_files->getId()}', this.actionn='{$logs_patient_files->getActionn()}', this.new_patient_id='{$logs_patient_files->getNew_patient_id()}', this.new_doctor_id='{$logs_patient_files->getNew_doctor_id()}', this.new_file_name='{$logs_patient_files->getNew_file_name()}', this.new_file_type='{$logs_patient_files->getNew_file_type()}', this.new_file_path='{$logs_patient_files->getNew_file_path()}', this.new_created_at='{$logs_patient_files->getNew_created_at()}', this.logs_cdate='{$logs_patient_files->getLogs_cdate()}', this.logs_ctime='{$logs_patient_files->getLogs_ctime()}', this.log_ByUser='{$logs_patient_files->getLog_ByUser()}', this.timee='{$logs_patient_files->getTimee()}', this.time='{$logs_patient_files->getTime()}'");}}

?>