<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_appointments_token'])){
    $_SESSION['logs_appointments_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_appointments_token_time'] = time() + 3600;
    exit($_SESSION['logs_appointments_token']);
  }

  if($_GET['token'] != $_SESSION['logs_appointments_token'] || $_SESSION['logs_appointments_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_appointments_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_appointments = new Logs_appointments();
  if(!empty($_GET['id'])){$logs_appointments->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_appointments->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_doctor_id'])){$logs_appointments->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_patient_id'])){$logs_appointments->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_appointment_date'])){$logs_appointments->setNew_appointment_date($_GET['new_appointment_date']);}
  if(!empty($_GET['new_appointment_type'])){$logs_appointments->setNew_appointment_type($_GET['new_appointment_type']);}
  if(!empty($_GET['new_doctor_name'])){$logs_appointments->setNew_doctor_name($_GET['new_doctor_name']);}
  if(!empty($_GET['on_date'])){$logs_appointments->setOn_date($_GET['on_date']);}
  if(!empty($_GET['new_notes'])){$logs_appointments->setNew_notes($_GET['new_notes']);}
  if(!empty($_GET['logs_cdate'])){$logs_appointments->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_appointments->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_appointments->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_appointments->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_appointments->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_appointments->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_appointments->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_appointments->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_appointments->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_appointments->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_appointments->getLastRow()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_appointments->getFirstRow()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_appointments->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_appointments->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_appointments->setId($_GET['getById']); if($logs_appointments->getById()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_appointments->setActionn($_GET['getByActionn']); if($logs_appointments->getByActionn()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_appointments->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_appointments->getByNew_doctor_id()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_appointments->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_appointments->getByNew_patient_id()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByNew_appointment_date'])){$logs_appointments->setNew_appointment_date($_GET['getByNew_appointment_date']); if($logs_appointments->getByNew_appointment_date()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByNew_appointment_type'])){$logs_appointments->setNew_appointment_type($_GET['getByNew_appointment_type']); if($logs_appointments->getByNew_appointment_type()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_name'])){$logs_appointments->setNew_doctor_name($_GET['getByNew_doctor_name']); if($logs_appointments->getByNew_doctor_name()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByOn_date'])){$logs_appointments->setOn_date($_GET['getByOn_date']); if($logs_appointments->getByOn_date()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByNew_notes'])){$logs_appointments->setNew_notes($_GET['getByNew_notes']); if($logs_appointments->getByNew_notes()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_appointments->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_appointments->getByLogs_cdate()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_appointments->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_appointments->getByLogs_ctime()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_appointments->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_appointments->getByLog_ByUser()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_appointments->setTimee($_GET['getByTimee']); if($logs_appointments->getByTimee()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_appointments->setTime($_GET['getByTime']); if($logs_appointments->getByTime()){exit("this.id='{$logs_appointments->getId()}', this.actionn='{$logs_appointments->getActionn()}', this.new_doctor_id='{$logs_appointments->getNew_doctor_id()}', this.new_patient_id='{$logs_appointments->getNew_patient_id()}', this.new_appointment_date='{$logs_appointments->getNew_appointment_date()}', this.new_appointment_type='{$logs_appointments->getNew_appointment_type()}', this.new_doctor_name='{$logs_appointments->getNew_doctor_name()}', this.on_date='{$logs_appointments->getOn_date()}', this.new_notes='{$logs_appointments->getNew_notes()}', this.logs_cdate='{$logs_appointments->getLogs_cdate()}', this.logs_ctime='{$logs_appointments->getLogs_ctime()}', this.log_ByUser='{$logs_appointments->getLog_ByUser()}', this.timee='{$logs_appointments->getTimee()}', this.time='{$logs_appointments->getTime()}'");}}

?>