<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_medical_procedures_token'])){
    $_SESSION['logs_medical_procedures_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_medical_procedures_token_time'] = time() + 3600;
    exit($_SESSION['logs_medical_procedures_token']);
  }

  if($_GET['token'] != $_SESSION['logs_medical_procedures_token'] || $_SESSION['logs_medical_procedures_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_medical_procedures_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_medical_procedures = new Logs_medical_procedures();
  if(!empty($_GET['id'])){$logs_medical_procedures->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_medical_procedures->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_medical_procedures->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_doctor_id'])){$logs_medical_procedures->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_procedure_date'])){$logs_medical_procedures->setNew_procedure_date($_GET['new_procedure_date']);}
  if(!empty($_GET['new_procedure_type'])){$logs_medical_procedures->setNew_procedure_type($_GET['new_procedure_type']);}
  if(!empty($_GET['new_procedure_notes'])){$logs_medical_procedures->setNew_procedure_notes($_GET['new_procedure_notes']);}
  if(!empty($_GET['logs_cdate'])){$logs_medical_procedures->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_medical_procedures->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_medical_procedures->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_medical_procedures->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_medical_procedures->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_medical_procedures->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_medical_procedures->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_medical_procedures->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_medical_procedures->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_medical_procedures->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_medical_procedures->getLastRow()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_medical_procedures->getFirstRow()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_medical_procedures->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_medical_procedures->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_medical_procedures->setId($_GET['getById']); if($logs_medical_procedures->getById()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_medical_procedures->setActionn($_GET['getByActionn']); if($logs_medical_procedures->getByActionn()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_medical_procedures->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_medical_procedures->getByNew_patient_id()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_medical_procedures->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_medical_procedures->getByNew_doctor_id()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByNew_procedure_date'])){$logs_medical_procedures->setNew_procedure_date($_GET['getByNew_procedure_date']); if($logs_medical_procedures->getByNew_procedure_date()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByNew_procedure_type'])){$logs_medical_procedures->setNew_procedure_type($_GET['getByNew_procedure_type']); if($logs_medical_procedures->getByNew_procedure_type()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByNew_procedure_notes'])){$logs_medical_procedures->setNew_procedure_notes($_GET['getByNew_procedure_notes']); if($logs_medical_procedures->getByNew_procedure_notes()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_medical_procedures->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_medical_procedures->getByLogs_cdate()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_medical_procedures->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_medical_procedures->getByLogs_ctime()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_medical_procedures->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_medical_procedures->getByLog_ByUser()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_medical_procedures->setTimee($_GET['getByTimee']); if($logs_medical_procedures->getByTimee()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_medical_procedures->setTime($_GET['getByTime']); if($logs_medical_procedures->getByTime()){exit("this.id='{$logs_medical_procedures->getId()}', this.actionn='{$logs_medical_procedures->getActionn()}', this.new_patient_id='{$logs_medical_procedures->getNew_patient_id()}', this.new_doctor_id='{$logs_medical_procedures->getNew_doctor_id()}', this.new_procedure_date='{$logs_medical_procedures->getNew_procedure_date()}', this.new_procedure_type='{$logs_medical_procedures->getNew_procedure_type()}', this.new_procedure_notes='{$logs_medical_procedures->getNew_procedure_notes()}', this.logs_cdate='{$logs_medical_procedures->getLogs_cdate()}', this.logs_ctime='{$logs_medical_procedures->getLogs_ctime()}', this.log_ByUser='{$logs_medical_procedures->getLog_ByUser()}', this.timee='{$logs_medical_procedures->getTimee()}', this.time='{$logs_medical_procedures->getTime()}'");}}

?>