<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_lab_tests_token'])){
    $_SESSION['logs_lab_tests_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_lab_tests_token_time'] = time() + 3600;
    exit($_SESSION['logs_lab_tests_token']);
  }

  if($_GET['token'] != $_SESSION['logs_lab_tests_token'] || $_SESSION['logs_lab_tests_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_lab_tests_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_lab_tests = new Logs_lab_tests();
  if(!empty($_GET['id'])){$logs_lab_tests->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_lab_tests->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_doctor_id'])){$logs_lab_tests->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_patient_id'])){$logs_lab_tests->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_test_name'])){$logs_lab_tests->setNew_test_name($_GET['new_test_name']);}
  if(!empty($_GET['new_test_results'])){$logs_lab_tests->setNew_test_results($_GET['new_test_results']);}
  if(!empty($_GET['new_test_date'])){$logs_lab_tests->setNew_test_date($_GET['new_test_date']);}
  if(!empty($_GET['logs_cdate'])){$logs_lab_tests->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_lab_tests->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_lab_tests->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_lab_tests->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_lab_tests->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_lab_tests->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_lab_tests->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_lab_tests->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_lab_tests->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_lab_tests->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_lab_tests->getLastRow()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_lab_tests->getFirstRow()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_lab_tests->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_lab_tests->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_lab_tests->setId($_GET['getById']); if($logs_lab_tests->getById()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_lab_tests->setActionn($_GET['getByActionn']); if($logs_lab_tests->getByActionn()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_lab_tests->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_lab_tests->getByNew_doctor_id()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_lab_tests->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_lab_tests->getByNew_patient_id()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByNew_test_name'])){$logs_lab_tests->setNew_test_name($_GET['getByNew_test_name']); if($logs_lab_tests->getByNew_test_name()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByNew_test_results'])){$logs_lab_tests->setNew_test_results($_GET['getByNew_test_results']); if($logs_lab_tests->getByNew_test_results()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByNew_test_date'])){$logs_lab_tests->setNew_test_date($_GET['getByNew_test_date']); if($logs_lab_tests->getByNew_test_date()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_lab_tests->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_lab_tests->getByLogs_cdate()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_lab_tests->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_lab_tests->getByLogs_ctime()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_lab_tests->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_lab_tests->getByLog_ByUser()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_lab_tests->setTimee($_GET['getByTimee']); if($logs_lab_tests->getByTimee()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_lab_tests->setTime($_GET['getByTime']); if($logs_lab_tests->getByTime()){exit("this.id='{$logs_lab_tests->getId()}', this.actionn='{$logs_lab_tests->getActionn()}', this.new_doctor_id='{$logs_lab_tests->getNew_doctor_id()}', this.new_patient_id='{$logs_lab_tests->getNew_patient_id()}', this.new_test_name='{$logs_lab_tests->getNew_test_name()}', this.new_test_results='{$logs_lab_tests->getNew_test_results()}', this.new_test_date='{$logs_lab_tests->getNew_test_date()}', this.logs_cdate='{$logs_lab_tests->getLogs_cdate()}', this.logs_ctime='{$logs_lab_tests->getLogs_ctime()}', this.log_ByUser='{$logs_lab_tests->getLog_ByUser()}', this.timee='{$logs_lab_tests->getTimee()}', this.time='{$logs_lab_tests->getTime()}'");}}

?>