<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_medications_token'])){
    $_SESSION['logs_medications_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_medications_token_time'] = time() + 3600;
    exit($_SESSION['logs_medications_token']);
  }

  if($_GET['token'] != $_SESSION['logs_medications_token'] || $_SESSION['logs_medications_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_medications_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_medications = new Logs_medications();
  if(!empty($_GET['id'])){$logs_medications->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_medications->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_doctor_id'])){$logs_medications->setNew_doctor_id($_GET['new_doctor_id']);}
  if(!empty($_GET['new_patient_id'])){$logs_medications->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_medication_name'])){$logs_medications->setNew_medication_name($_GET['new_medication_name']);}
  if(!empty($_GET['new_dosage'])){$logs_medications->setNew_dosage($_GET['new_dosage']);}
  if(!empty($_GET['new_frequency'])){$logs_medications->setNew_frequency($_GET['new_frequency']);}
  if(!empty($_GET['new_start_date'])){$logs_medications->setNew_start_date($_GET['new_start_date']);}
  if(!empty($_GET['new_end_date'])){$logs_medications->setNew_end_date($_GET['new_end_date']);}
  if(!empty($_GET['logs_cdate'])){$logs_medications->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_medications->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_medications->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_medications->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_medications->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_medications->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_medications->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_medications->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_medications->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_medications->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_medications->getLastRow()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_medications->getFirstRow()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_medications->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_medications->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_medications->setId($_GET['getById']); if($logs_medications->getById()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_medications->setActionn($_GET['getByActionn']); if($logs_medications->getByActionn()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_doctor_id'])){$logs_medications->setNew_doctor_id($_GET['getByNew_doctor_id']); if($logs_medications->getByNew_doctor_id()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_medications->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_medications->getByNew_patient_id()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_medication_name'])){$logs_medications->setNew_medication_name($_GET['getByNew_medication_name']); if($logs_medications->getByNew_medication_name()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_dosage'])){$logs_medications->setNew_dosage($_GET['getByNew_dosage']); if($logs_medications->getByNew_dosage()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_frequency'])){$logs_medications->setNew_frequency($_GET['getByNew_frequency']); if($logs_medications->getByNew_frequency()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_start_date'])){$logs_medications->setNew_start_date($_GET['getByNew_start_date']); if($logs_medications->getByNew_start_date()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByNew_end_date'])){$logs_medications->setNew_end_date($_GET['getByNew_end_date']); if($logs_medications->getByNew_end_date()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_medications->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_medications->getByLogs_cdate()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_medications->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_medications->getByLogs_ctime()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_medications->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_medications->getByLog_ByUser()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_medications->setTimee($_GET['getByTimee']); if($logs_medications->getByTimee()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_medications->setTime($_GET['getByTime']); if($logs_medications->getByTime()){exit("this.id='{$logs_medications->getId()}', this.actionn='{$logs_medications->getActionn()}', this.new_doctor_id='{$logs_medications->getNew_doctor_id()}', this.new_patient_id='{$logs_medications->getNew_patient_id()}', this.new_medication_name='{$logs_medications->getNew_medication_name()}', this.new_dosage='{$logs_medications->getNew_dosage()}', this.new_frequency='{$logs_medications->getNew_frequency()}', this.new_start_date='{$logs_medications->getNew_start_date()}', this.new_end_date='{$logs_medications->getNew_end_date()}', this.logs_cdate='{$logs_medications->getLogs_cdate()}', this.logs_ctime='{$logs_medications->getLogs_ctime()}', this.log_ByUser='{$logs_medications->getLog_ByUser()}', this.timee='{$logs_medications->getTimee()}', this.time='{$logs_medications->getTime()}'");}}

?>