<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_users_token'])){
    $_SESSION['logs_users_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_users_token_time'] = time() + 3600;
    exit($_SESSION['logs_users_token']);
  }

  if($_GET['token'] != $_SESSION['logs_users_token'] || $_SESSION['logs_users_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_users_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_users = new Logs_users();
  if(!empty($_GET['id'])){$logs_users->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_users->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_username'])){$logs_users->setNew_username($_GET['new_username']);}
  if(!empty($_GET['new_email'])){$logs_users->setNew_email($_GET['new_email']);}
  if(!empty($_GET['new_password'])){$logs_users->setNew_password($_GET['new_password']);}
  if(!empty($_GET['new_role'])){$logs_users->setNew_role($_GET['new_role']);}
  if(!empty($_GET['new_created_at'])){$logs_users->setNew_created_at($_GET['new_created_at']);}
  if(!empty($_GET['logs_cdate'])){$logs_users->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_users->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_users->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_users->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_users->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_users->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_users->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_users->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_users->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_users->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_users->getLastRow()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_users->getFirstRow()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_users->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_users->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_users->setId($_GET['getById']); if($logs_users->getById()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_users->setActionn($_GET['getByActionn']); if($logs_users->getByActionn()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByNew_username'])){$logs_users->setNew_username($_GET['getByNew_username']); if($logs_users->getByNew_username()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByNew_email'])){$logs_users->setNew_email($_GET['getByNew_email']); if($logs_users->getByNew_email()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByNew_password'])){$logs_users->setNew_password($_GET['getByNew_password']); if($logs_users->getByNew_password()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByNew_role'])){$logs_users->setNew_role($_GET['getByNew_role']); if($logs_users->getByNew_role()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByNew_created_at'])){$logs_users->setNew_created_at($_GET['getByNew_created_at']); if($logs_users->getByNew_created_at()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_users->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_users->getByLogs_cdate()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_users->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_users->getByLogs_ctime()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_users->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_users->getByLog_ByUser()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_users->setTimee($_GET['getByTimee']); if($logs_users->getByTimee()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_users->setTime($_GET['getByTime']); if($logs_users->getByTime()){exit("this.id='{$logs_users->getId()}', this.actionn='{$logs_users->getActionn()}', this.new_username='{$logs_users->getNew_username()}', this.new_email='{$logs_users->getNew_email()}', this.new_password='{$logs_users->getNew_password()}', this.new_role='{$logs_users->getNew_role()}', this.new_created_at='{$logs_users->getNew_created_at()}', this.logs_cdate='{$logs_users->getLogs_cdate()}', this.logs_ctime='{$logs_users->getLogs_ctime()}', this.log_ByUser='{$logs_users->getLog_ByUser()}', this.timee='{$logs_users->getTimee()}', this.time='{$logs_users->getTime()}'");}}

?>