<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['logs_vitals_token'])){
    $_SESSION['logs_vitals_token'] = bin2hex(random_bytes(32));
    $_SESSION['logs_vitals_token_time'] = time() + 3600;
    exit($_SESSION['logs_vitals_token']);
  }

  if($_GET['token'] != $_SESSION['logs_vitals_token'] || $_SESSION['logs_vitals_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['logs_vitals_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $logs_vitals = new Logs_vitals();
  if(!empty($_GET['id'])){$logs_vitals->setId($_GET['id']);}
  if(!empty($_GET['actionn'])){$logs_vitals->setActionn($_GET['actionn']);}
  if(!empty($_GET['new_patient_id'])){$logs_vitals->setNew_patient_id($_GET['new_patient_id']);}
  if(!empty($_GET['new_date_time'])){$logs_vitals->setNew_date_time($_GET['new_date_time']);}
  if(!empty($_GET['new_temperature'])){$logs_vitals->setNew_temperature($_GET['new_temperature']);}
  if(!empty($_GET['new_blood_pressure'])){$logs_vitals->setNew_blood_pressure($_GET['new_blood_pressure']);}
  if(!empty($_GET['new_heart_rate'])){$logs_vitals->setNew_heart_rate($_GET['new_heart_rate']);}
  if(!empty($_GET['new_respiratory_rate'])){$logs_vitals->setNew_respiratory_rate($_GET['new_respiratory_rate']);}
  if(!empty($_GET['logs_cdate'])){$logs_vitals->setLogs_cdate($_GET['logs_cdate']);}
  if(!empty($_GET['logs_ctime'])){$logs_vitals->setLogs_ctime($_GET['logs_ctime']);}
  if(!empty($_GET['log_ByUser'])){$logs_vitals->setLog_ByUser($_GET['log_ByUser']);}
  if(!empty($_GET['timee'])){$logs_vitals->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$logs_vitals->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$logs_vitals->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$logs_vitals->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$logs_vitals->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($logs_vitals->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($logs_vitals->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($logs_vitals->getLastRow()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($logs_vitals->getFirstRow()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($logs_vitals->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$logs_vitals->getNumberOfRows());}
  if(!empty($_GET['getById'])){$logs_vitals->setId($_GET['getById']); if($logs_vitals->getById()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByActionn'])){$logs_vitals->setActionn($_GET['getByActionn']); if($logs_vitals->getByActionn()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByNew_patient_id'])){$logs_vitals->setNew_patient_id($_GET['getByNew_patient_id']); if($logs_vitals->getByNew_patient_id()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByNew_date_time'])){$logs_vitals->setNew_date_time($_GET['getByNew_date_time']); if($logs_vitals->getByNew_date_time()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByNew_temperature'])){$logs_vitals->setNew_temperature($_GET['getByNew_temperature']); if($logs_vitals->getByNew_temperature()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByNew_blood_pressure'])){$logs_vitals->setNew_blood_pressure($_GET['getByNew_blood_pressure']); if($logs_vitals->getByNew_blood_pressure()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByNew_heart_rate'])){$logs_vitals->setNew_heart_rate($_GET['getByNew_heart_rate']); if($logs_vitals->getByNew_heart_rate()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByNew_respiratory_rate'])){$logs_vitals->setNew_respiratory_rate($_GET['getByNew_respiratory_rate']); if($logs_vitals->getByNew_respiratory_rate()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByLogs_cdate'])){$logs_vitals->setLogs_cdate($_GET['getByLogs_cdate']); if($logs_vitals->getByLogs_cdate()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByLogs_ctime'])){$logs_vitals->setLogs_ctime($_GET['getByLogs_ctime']); if($logs_vitals->getByLogs_ctime()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByLog_ByUser'])){$logs_vitals->setLog_ByUser($_GET['getByLog_ByUser']); if($logs_vitals->getByLog_ByUser()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$logs_vitals->setTimee($_GET['getByTimee']); if($logs_vitals->getByTimee()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$logs_vitals->setTime($_GET['getByTime']); if($logs_vitals->getByTime()){exit("this.id='{$logs_vitals->getId()}', this.actionn='{$logs_vitals->getActionn()}', this.new_patient_id='{$logs_vitals->getNew_patient_id()}', this.new_date_time='{$logs_vitals->getNew_date_time()}', this.new_temperature='{$logs_vitals->getNew_temperature()}', this.new_blood_pressure='{$logs_vitals->getNew_blood_pressure()}', this.new_heart_rate='{$logs_vitals->getNew_heart_rate()}', this.new_respiratory_rate='{$logs_vitals->getNew_respiratory_rate()}', this.logs_cdate='{$logs_vitals->getLogs_cdate()}', this.logs_ctime='{$logs_vitals->getLogs_ctime()}', this.log_ByUser='{$logs_vitals->getLog_ByUser()}', this.timee='{$logs_vitals->getTimee()}', this.time='{$logs_vitals->getTime()}'");}}

?>