<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['medical_records_token'])){
    $_SESSION['medical_records_token'] = bin2hex(random_bytes(32));
    $_SESSION['medical_records_token_time'] = time() + 3600;
    exit($_SESSION['medical_records_token']);
  }

  if($_GET['token'] != $_SESSION['medical_records_token'] || $_SESSION['medical_records_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['medical_records_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $medical_records = new Medical_records();
  if(!empty($_GET['id'])){$medical_records->setId($_GET['id']);}
  if(!empty($_GET['doctor_id'])){$medical_records->setDoctor_id($_GET['doctor_id']);}
  if(!empty($_GET['patient_id'])){$medical_records->setPatient_id($_GET['patient_id']);}
  if(!empty($_GET['record_date'])){$medical_records->setRecord_date($_GET['record_date']);}
  if(!empty($_GET['medical_condition'])){$medical_records->setMedical_condition($_GET['medical_condition']);}
  if(!empty($_GET['height'])){$medical_records->setHeight($_GET['height']);}
  if(!empty($_GET['weight'])){$medical_records->setWeight($_GET['weight']);}
  if(!empty($_GET['blood_pressure'])){$medical_records->setBlood_pressure($_GET['blood_pressure']);}
  if(!empty($_GET['blood_sugar'])){$medical_records->setBlood_sugar($_GET['blood_sugar']);}
  if(!empty($_GET['treatment'])){$medical_records->setTreatment($_GET['treatment']);}
  if(!empty($_GET['description'])){$medical_records->setDescription($_GET['description']);}
  if(!empty($_GET['diagnosis_date'])){$medical_records->setDiagnosis_date($_GET['diagnosis_date']);}
  if(!empty($_GET['timee'])){$medical_records->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$medical_records->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$medical_records->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$medical_records->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$medical_records->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($medical_records->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($medical_records->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($medical_records->getLastRow()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($medical_records->getFirstRow()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($medical_records->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$medical_records->getNumberOfRows());}
  if(!empty($_GET['getById'])){$medical_records->setId($_GET['getById']); if($medical_records->getById()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByDoctor_id'])){$medical_records->setDoctor_id($_GET['getByDoctor_id']); if($medical_records->getByDoctor_id()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByPatient_id'])){$medical_records->setPatient_id($_GET['getByPatient_id']); if($medical_records->getByPatient_id()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByRecord_date'])){$medical_records->setRecord_date($_GET['getByRecord_date']); if($medical_records->getByRecord_date()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByMedical_condition'])){$medical_records->setMedical_condition($_GET['getByMedical_condition']); if($medical_records->getByMedical_condition()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByHeight'])){$medical_records->setHeight($_GET['getByHeight']); if($medical_records->getByHeight()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByWeight'])){$medical_records->setWeight($_GET['getByWeight']); if($medical_records->getByWeight()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByBlood_pressure'])){$medical_records->setBlood_pressure($_GET['getByBlood_pressure']); if($medical_records->getByBlood_pressure()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByBlood_sugar'])){$medical_records->setBlood_sugar($_GET['getByBlood_sugar']); if($medical_records->getByBlood_sugar()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByTreatment'])){$medical_records->setTreatment($_GET['getByTreatment']); if($medical_records->getByTreatment()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByDescription'])){$medical_records->setDescription($_GET['getByDescription']); if($medical_records->getByDescription()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByDiagnosis_date'])){$medical_records->setDiagnosis_date($_GET['getByDiagnosis_date']); if($medical_records->getByDiagnosis_date()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$medical_records->setTimee($_GET['getByTimee']); if($medical_records->getByTimee()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$medical_records->setTime($_GET['getByTime']); if($medical_records->getByTime()){exit("this.id='{$medical_records->getId()}', this.doctor_id='{$medical_records->getDoctor_id()}', this.patient_id='{$medical_records->getPatient_id()}', this.record_date='{$medical_records->getRecord_date()}', this.medical_condition='{$medical_records->getMedical_condition()}', this.height='{$medical_records->getHeight()}', this.weight='{$medical_records->getWeight()}', this.blood_pressure='{$medical_records->getBlood_pressure()}', this.blood_sugar='{$medical_records->getBlood_sugar()}', this.treatment='{$medical_records->getTreatment()}', this.description='{$medical_records->getDescription()}', this.diagnosis_date='{$medical_records->getDiagnosis_date()}', this.timee='{$medical_records->getTimee()}', this.time='{$medical_records->getTime()}'");}}

?>