<?php

  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/autoloader.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/secuerity.inc.php';
  include_once $_SERVER["DOCUMENT_ROOT"].'/includes/time.inc.php';

  // CSRF TOKEN SECURITY
  if(empty($_GET['token']) || empty($_SESSION['patients_token'])){
    $_SESSION['patients_token'] = bin2hex(random_bytes(32));
    $_SESSION['patients_token_time'] = time() + 3600;
    exit($_SESSION['patients_token']);
  }

  if($_GET['token'] != $_SESSION['patients_token'] || $_SESSION['patients_token_time'] <= time()){
    exit("this.msg='error_token_invaild'");
  }

  $_SESSION['patients_token'] = '';

  // DELETE THE LINES THAT IS USING FOR AUTHENTICATIONS LIKE PASSWORD OR SOMETHING THAT PUT YOUR WORK IN DANGER IF IT WILL BE GETTED BY JAVASCRIPT
  $patients = new Patients();
  if(!empty($_GET['id'])){$patients->setId($_GET['id']);}
  if(!empty($_GET['user_id'])){$patients->setUser_id($_GET['user_id']);}
  if(!empty($_GET['first_name'])){$patients->setFirst_name($_GET['first_name']);}
  if(!empty($_GET['middle_name'])){$patients->setMiddle_name($_GET['middle_name']);}
  if(!empty($_GET['last_name'])){$patients->setLast_name($_GET['last_name']);}
  if(!empty($_GET['date_of_birth'])){$patients->setDate_of_birth($_GET['date_of_birth']);}
  if(!empty($_GET['gender'])){$patients->setGender($_GET['gender']);}
  if(!empty($_GET['address'])){$patients->setAddress($_GET['address']);}
  if(!empty($_GET['city'])){$patients->setCity($_GET['city']);}
  if(!empty($_GET['zip_code'])){$patients->setZip_code($_GET['zip_code']);}
  if(!empty($_GET['phone_number'])){$patients->setPhone_number($_GET['phone_number']);}
  if(!empty($_GET['email'])){$patients->setEmail($_GET['email']);}
  if(!empty($_GET['timee'])){$patients->setTimee($_GET['timee']);}
  if(!empty($_GET['time'])){$patients->setTime($_GET['time']);}
  // SET FUNCTIONS MUST BE ABOVE OF THE FOLLOWING LINES
  if(!empty($_GET['add'])){if(!$patients->add()){exit("this.error=1; this.msg='add'");}}
  if(!empty($_GET['update'])){if(!$patients->update()){exit("this.error=1; this.msg='update'");}}
  if(!empty($_GET['delete'])){if(!$patients->delete()){exit("this.error=1; this.msg='delete'");}}
  if(!empty($_GET['getBySet'])){echo json_encode($patients->getBySet($_GET['getBySet']));}
  if(!empty($_GET['getAll'])){echo json_encode($patients->getAll($_GET['getAll']));}
  if(!empty($_GET['getLastRow'])){if($patients->getLastRow()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getFirstRow'])){if($patients->getFirstRow()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getAllReversed'])){echo json_encode($patients->getAllReversed($_GET['getAllReversed']));}
  if(!empty($_GET['getNumberOfRows'])){exit(''.$patients->getNumberOfRows());}
  if(!empty($_GET['getById'])){$patients->setId($_GET['getById']); if($patients->getById()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByUser_id'])){$patients->setUser_id($_GET['getByUser_id']); if($patients->getByUser_id()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByFirst_name'])){$patients->setFirst_name($_GET['getByFirst_name']); if($patients->getByFirst_name()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByMiddle_name'])){$patients->setMiddle_name($_GET['getByMiddle_name']); if($patients->getByMiddle_name()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByLast_name'])){$patients->setLast_name($_GET['getByLast_name']); if($patients->getByLast_name()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByDate_of_birth'])){$patients->setDate_of_birth($_GET['getByDate_of_birth']); if($patients->getByDate_of_birth()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByGender'])){$patients->setGender($_GET['getByGender']); if($patients->getByGender()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByAddress'])){$patients->setAddress($_GET['getByAddress']); if($patients->getByAddress()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByCity'])){$patients->setCity($_GET['getByCity']); if($patients->getByCity()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByZip_code'])){$patients->setZip_code($_GET['getByZip_code']); if($patients->getByZip_code()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByPhone_number'])){$patients->setPhone_number($_GET['getByPhone_number']); if($patients->getByPhone_number()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByEmail'])){$patients->setEmail($_GET['getByEmail']); if($patients->getByEmail()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByTimee'])){$patients->setTimee($_GET['getByTimee']); if($patients->getByTimee()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}
  if(!empty($_GET['getByTime'])){$patients->setTime($_GET['getByTime']); if($patients->getByTime()){exit("this.id='{$patients->getId()}', this.user_id='{$patients->getUser_id()}', this.first_name='{$patients->getFirst_name()}', this.middle_name='{$patients->getMiddle_name()}', this.last_name='{$patients->getLast_name()}', this.date_of_birth='{$patients->getDate_of_birth()}', this.gender='{$patients->getGender()}', this.address='{$patients->getAddress()}', this.city='{$patients->getCity()}', this.zip_code='{$patients->getZip_code()}', this.phone_number='{$patients->getPhone_number()}', this.email='{$patients->getEmail()}', this.timee='{$patients->getTimee()}', this.time='{$patients->getTime()}'");}}

?>